export const MODAL_ACTIONS = {
  MODAL_SUCCESS: 'MODAL_ACTIONS/MODAL_SUCCESS',
  MODAL_ERROR: 'MODAL_ACTIONS/MODAL_ERROR',
  MODAL_CLOSE: 'MODAL_ACTIONS/MODAL_CLOSE',
  MODAL_OPEN: 'MODAL_ACTIONS/MODAL_OPEN',
} as const;
