FROM node:14-alpine

WORKDIR /app

COPY ["package.json","package-lock.json*","npm-shrinkwrap.json*", "./"]

RUN npm install && npm cache clean --force

COPY . .

EXPOSE 5000

CMD [ "npm", "run", "dev" ]