// TODO Enums 

export const GET_BOOKS_SUCCESS = 'GET_BOOKS_SUCCESS';
export const GET_BOOKS_REQUEST = 'GET_BOOKS_REQUEST';
export const GET_BOOKS_ERROR = 'GET_BOOKS_ERROR';
export const GET_ONE_BOOK_SUCCESS = 'GET_ONE_BOOK_SUCCESS';
export const REMOVE_ONE_BOOK_SUCCESS = 'REMOVE_ONE_BOOK_SUCCES';
export const REMOVE_ONE_BOOK_ERROR = 'REMOVE_ONE_BOOK_ERROR';

export const CHANGE_NAME = 'CHANGE_NAME';
export const SWITCH_THEME = 'SWITCH_THEME'