export const BOOKS_ACTIONS = {
  FETCH_BOOKS: 'BOOKS_ACTIONS/FETCH_BOOKS',
  FETCH_ONE_BOOK: 'BOOKS_ACTIONS/FETCH_ONE_BOOK',
  BOOK_REMOVE: 'BOOKS_ACTIONS/BOOK_REMOVE',
  BOOK_CLEAR_STORE: 'BOOKS_ACTIONS/BOOK_CLEAR_STORE',
  SET_LOADING_STATUS: 'BOOKS_ACTIONS/SET_LOADING_STATUS',
  SET_PARAMETERS: 'BOOKS_ACTIONS/SET_PARAMETERS',
} as const;
